### PR TITLE
add update seller-fee-basis-points-all

### PR DESCRIPTION
**Pull request by CrowdedRoom**
This PR adds the ability to update the sellers fee on a JSON list of mints and new seller fees, similar to the update uri-all. 

`
[
    {
        "mint_account": "5tQKjHyJx9..........wuDdXr3kHd",
        "new_seller_fee_basis_points": 1000
    },
    {
        "mint_account": "5n2gDhH.........twnCAqzKYhTrGnV",
        "new_seller_fee_basis_points": 1000
    }
]
`

### CODE REVIEW

**Comment by samuelvanderwaal** [comment]
Thanks for the PR! I will review this in the next day or so.

**Comment by samuelvanderwaal** [comment]
Sorry for the delay in reviewing this! I tested it out and it seems to work well but I have a couple of thoughts and suggestions:

`update seller-fee-basis-points-all` is pretty onerous to have write out as a command, what about shortening both to `update sfbp` and `update sfbp-all`? Then if people don't know what that means they can always run `-h` and the docs comments will explain.
Alternately, we could rename the command something else entirely such as `royalty` but that might be less intuitive for people who are used to the `seller fee basis points` terminology.

The vast majority of collections I've seen use the same seller fee basis points number for their entire collection instead of having individual ones, so I think the default should be for this command to just take a mint list and update the same value to all of them. If you think there's a good reason to be able to specify individual ones maybe that can be an alternate format, but making it the default seems like it would be a lot of work for most folks who are going to use the same value for all items in the collection.

Thoughts?

**Comment by CrowdedRoom** [comment]
Yeah I tend to agree on just setting it to a single value for the whole list. That would likely be the main use case. I should be able to get that updated after vacation.

I'm ok with the rename also. I think **sfbp** would be better than **royalty**, maybe there is a better option all together, but that could always be done in a separate PR after more consensus

**Comment by samuelvanderwaal** [comment]
@CrowdedRoom, let me know before you spend more time on this, I just got my async trait working to make it easier for me to refactor all the update commands to be async, so I may get to this command soon.

**Comment by samuelvanderwaal** [comment]
Really sorry to rug you, but wasn't sure when you'd get back from vacation and just merged an `update sfbp-all` command based on the new async pattern I've been working on.

**Pull request closed without merging**
