### PR TITLE
Implement new Metadata API

### PR DESCRIPTION
**Pull request by sunguru98**
Implemented the following instructions

1) revoke_use_authority
2) accept_use_authority
3) utilize
4) set_and_verify_collection
5) verify_collection
6) unverify_collection

### CODE REVIEW

**Comment by sunguru98** [comment]
Transactions for testing both collections and uses are included beneath

1. set_and_verify -> [Tx](https://solscan.io/tx/39SJfXyhuyEh2SMSbpgXBY62EfAmZsajt4aDipHB9NzxLvHyQq8rnPWqMv2Rn5tvovCdWv7dp9j2abdWMbN9U7g1?cluster=devnet)

2. unverify_collection -> [Tx](https://solscan.io/tx/3XBdpNnD4KJgV2yJdVHUUMb5rVtyLWFgEUDe9w84s7QrBpvwrRfLheDzsymDg9mn2g6gGzwFjW3NmGqoMvBkFkjQ?cluster=devnet)

3. verify_collection -> [Tx](https://solscan.io/tx/559sPKPiM7284VCX3F5PmiSviyZK2ZCUTMS5SryuZRe7aq4jk6r2BoqmU6z7dBkKvAtYJE45nj1o3zF9hK3Cf7AYA?cluster=devnet)

4. approve_use_authority -> [Tx](https://solscan.io/tx/5Zf7Q6txknysxMk4y4eTsB3xK4PHRLr1S6mciAk4m56RkEdxYfknPshbHersvj9E8AsJtTiZo5Ez1PTfgcUuKpQC?cluster=devnet)

5. revoke_use_authority -> [Tx](https://solscan.io/tx/4daVvXFwb68GsygBLZQwodTwB2GxR7Gmig3b5wYG7zLv9QUq6FNWL3W9Sp7u3CzTRWiFkBE4sTADR3sNhsPai2rN?cluster=devnet)

6. utilize (with delegate) -> [Tx]
(https://solscan.io/tx/4Q7FBGABrXuctMnoNuhTYndRfJcQVz8SFDFQi4wULwv3VrECSfXF3k4gG8ucU8VEZ9YbL5KHwFkckXygHhfwTSdq?cluster=devnet)

7. utilize (without delegate) -> [Tx](https://solscan.io/tx/2AbEcGENGq2AaLAWXxnP4MAYfNLkjMiYcaoTizPV84YBX7oMtsBzaNKieauL92p9kCkMLPa9qEJgSeUzbvTBX5tM?cluster=devnet)

**Comment by sunguru98** [comment]
Transactions for testing both collections and uses are included beneath

1. set_and_verify -> [Tx](https://solscan.io/tx/39SJfXyhuyEh2SMSbpgXBY62EfAmZsajt4aDipHB9NzxLvHyQq8rnPWqMv2Rn5tvovCdWv7dp9j2abdWMbN9U7g1?cluster=devnet)

2. unverify_collection -> [Tx](https://solscan.io/tx/3XBdpNnD4KJgV2yJdVHUUMb5rVtyLWFgEUDe9w84s7QrBpvwrRfLheDzsymDg9mn2g6gGzwFjW3NmGqoMvBkFkjQ?cluster=devnet)

3. verify_collection -> [Tx](https://solscan.io/tx/559sPKPiM7284VCX3F5PmiSviyZK2ZCUTMS5SryuZRe7aq4jk6r2BoqmU6z7dBkKvAtYJE45nj1o3zF9hK3Cf7AYA?cluster=devnet)

4. approve_use_authority -> [Tx](https://solscan.io/tx/5Zf7Q6txknysxMk4y4eTsB3xK4PHRLr1S6mciAk4m56RkEdxYfknPshbHersvj9E8AsJtTiZo5Ez1PTfgcUuKpQC?cluster=devnet)

5. revoke_use_authority -> [Tx](https://solscan.io/tx/4daVvXFwb68GsygBLZQwodTwB2GxR7Gmig3b5wYG7zLv9QUq6FNWL3W9Sp7u3CzTRWiFkBE4sTADR3sNhsPai2rN?cluster=devnet)

6. utilize (with delegate) -> [Tx]
(https://solscan.io/tx/4Q7FBGABrXuctMnoNuhTYndRfJcQVz8SFDFQi4wULwv3VrECSfXF3k4gG8ucU8VEZ9YbL5KHwFkckXygHhfwTSdq?cluster=devnet)

7. utilize (without delegate) -> [Tx](https://solscan.io/tx/2AbEcGENGq2AaLAWXxnP4MAYfNLkjMiYcaoTizPV84YBX7oMtsBzaNKieauL92p9kCkMLPa9qEJgSeUzbvTBX5tM?cluster=devnet)

**Comment by sunguru98** [comment]
Ready for review @samuelvanderwaal :)

**Comment by samuelvanderwaal** [comment]
I reviewed the `collections` code and ran tests and everything checked out. I'll get to the `uses` today or tomorrow and then it will be good for merging. Thanks for your patience!

**Comment by sunguru98** [comment]
Sounds good. No problemo ser :)

**Pull request merged**
