### PR TITLE
feat(update): Update seller fee basis points of existing token

### PR DESCRIPTION
**Pull request by MCanhisares**
### Description:
Creating command to quickly update seller fee basis points of minted token

### Usage:
`metaboss update sellerfeebasispoints --keypair <PATH_TO_KEYPAIR> --account <MINT_ACCOUNT> -s <NEW_PRICE>`

### CODE REVIEW

**Comment by samuelvanderwaal** [comment]
Thanks for the PR! The code looks good but the problem with this approach is it doesn't also update the `seller_fee_basis_points` in the external metadata which allows the two to get out of sync. This could cause issues depending on if third parties such as marketplaces use the external metadata or the on-chain metadata. (In theory, on-chain metadata should have priority but I'm not sure we can guarantee all implementations actually do that.)

See [this](https://docs.metaplex.com/nft-standard) for the external metadata format.

One simple solution would be to also accept a `uri` argument putting the onus on the user to ensure they keep the two values in-sync:

```bash
metaboss update seller-fee-basis-points -k <PATH_TO_KEYPAIR> -a <MINT_ACCOUNT> -s <NEW_BASIS> -u <NEW_URI>
```

Thoughts?

**Comment by MCanhisares** [comment]
> Thanks for the PR! The code looks good but the problem with this approach is it doesn't also update the `seller_fee_basis_points` in the external metadata which allows the two to get out of sync. This could cause issues depending on if third parties such as marketplaces use the external metadata or the on-chain metadata. (In theory, on-chain metadata should have priority but I'm not sure we can guarantee all implementations actually do that.)
> 
> See [this](https://docs.metaplex.com/nft-standard) for the external metadata format.
> 
> One simple solution would be to also accept a `uri` argument putting the onus on the user to ensure they keep the two values in-sync:
> 
> ```shell
> metaboss update seller-fee-basis-points -k <PATH_TO_KEYPAIR> -a <MINT_ACCOUNT> -s <NEW_BASIS> -u <NEW_URI>
> ```
> 
> Thoughts?

Hey! 
Yea; I completely agree with your point; I think we can add an observation and this instruction to ensure that the user knows what he's doing.
I initially developed this because there's an issue with the metaplex upload/create CM flow where if you update your JSON's with the right `seller_fee_basis_points`, it only updates the uri that points to the new JSON and doesn't rewrite the `seller_fee_basis_points` on the SPL token 😞 
I don't think its this repo's responsibility to create and upload a new json to arweave; only updating the metadata itself is already a big hassle and this tool suite is a saver. 
I'll update the instructions and code to accept a new uri 👍

**Comment by OzanGulec** [comment]
MCanhisares, can you also include a way to change who gets the secondary sale royalties in your updates?

In my NFT series, I want to transfer the rights to get royalties to initial minters.

**Comment by samuelvanderwaal** [comment]
> MCanhisares, can you also include a way to change who gets the secondary sale royalties in your updates?
> 
> In my NFT series, I want to transfer the rights to get royalties to initial minters.

You can already do this with `update data`.

**Comment by samuelvanderwaal** [comment]
Closing for inactivity. If you're still planning on implementing this you can reopen it but you'll probably need to rebase your PR onto the latest code on `main` as there's been quite a few updates since you opened this.

**Pull request closed without merging**
