### PR TITLE
docs: remove justmint.xyz (site not resolving)

### PR DESCRIPTION
**Pull request by statikdev**

### CODE REVIEW

**Comment by samuelvanderwaal** [comment]
Sorry I missed this. Looks like NFT Armory is also not resolving now. :-( Let me see if I can find some other mint site to reference instead, otherwise this looks good and I appreciate the PR!

**Review by samuelvanderwaal — APPROVED** [review]

**Comment by samuelvanderwaal** [comment]
> https://sol-tools.tonyboyle.io/nft-tools/create-nft is working fine and Tony is working on improvements and additional features regularly. Maybe this should be added instead.

Good suggestion! @statikdev when you get a chance if you want to update this to replace those two links that don't resolve with Tony's tool I'll merge the PR. Thanks!

**Comment by statikdev** [comment]
@samuelvanderwaal | my bad, i never saw this notification.

**Comment by samuelvanderwaal** [comment]
> @samuelvanderwaal | my bad, i never saw this notification.

No worries!

**Pull request merged**
